"use client";
import React from "react";
import "./styles/globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { useTheme } from "@/components";
import { EnglishLanguage } from "@/lang";
import { IntlProvider } from "react-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [theme] = useTheme();

  return (
    <html lang="en" className={theme}>
      <Script src="/bg-animation.js" />
      <body>
        <canvas id="mosaicCanvas" />
        <IntlProvider messages={EnglishLanguage} locale="en" defaultLocale="en">
          {children}
        </IntlProvider>
      </body>
    </html>
  );
}
